version: '3.9'

services:
  healthy-db:
    image: postgres:14-alpine
    container_name: healthy-db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data

  redis:
    build:
      context: ./redis
      dockerfile: Dockerfile
    container_name: redis
    restart: always
    ports:
      - '6379:6379'
    networks:
      - default
    volumes:
      - redis-data:/data
    environment:
      - REDIS_PASSWORD=password

  redisinsight:
    image: redislabs/redisinsight:latest
    container_name: redisinsight
    restart: always
    depends_on:
      - redis
    ports:
      - '5540:5540'
    networks:
      - default
    volumes:
      - redisinsight-data:/data
    environment:
      - REDIS_PORT=6379
      - REDIS_PASSWORD=password

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: always
    ports:
      - '9090:9090'
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - default

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: always
    ports:
      - '3000:3000'
    depends_on:
      - prometheus
    networks:
      - default
    volumes:
      - grafana-storage:/var/lib/grafana
#    environment:
#      - GF_SECURITY_ADMIN_USER=admin
#      - GF_SECURITY_ADMIN_PASSWORD=admin_password

  nest-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest-app
    restart: always
    ports:
      - '3001:3001'
    depends_on:
      - healthy-db
      - redis
    networks:
      - default
    env_file: .env

networks:
  default:
    driver: bridge

volumes:
  db:
    driver: local
  redis-data:
    driver: local
  redisinsight-data:
    driver: local
  grafana-storage:
    driver: local
