groups:
  - name: application_metrics
    rules:
      - alert: HighDBQueryLatency
        expr: rate(pg_stat_activity{datname="postgres"}[5m]) > 0.5
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "High Database Query Latency"
          description: "Database query latency is higher than expected for more than 2 minutes."

      - alert: HighRedisMemoryUsage
        expr: redis_memory_used_bytes > 500000000
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "High Redis Memory Usage"
          description: "Redis memory usage is above 500MB for more than 2 minutes."

      - alert: RedisInstanceDown
        expr: redis_up == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Redis instance down"
          description: "Redis instance has been down for more than 1 minute."
