@startuml
skinparam linetype ortho

package "Веб-сайт Healthy: Angular" {
    [Веб-интерфейс]
}

package "Сервер Healthy: NestJS" {
    [Контроллеры]
    [Сервисы]
    [Сервис авторизации]
    [Сервис уведомлений]
    [Сервис управления учетными записями]
    [Сервис вакцин]
    [Сервис управления вакцинациями]
    [Сервис для управления файлами]
}

package "Сервер базы данных: PostgreSQL" {
    [База данных]
}

[Веб-интерфейс] -down-> [Контроллеры]
[Контроллеры] -down-> [Сервис авторизации]
[Контроллеры] -down-> [Сервис уведомлений]
[Контроллеры] -down-> [Сервис управления учетными записями]
[Контроллеры] -down-> [Сервис вакцин]
[Контроллеры] -down-> [Сервис управления вакцинациями]
[Контроллеры] -down-> [Сервис для управления файлами]
[Сервис авторизации] -down-> [База данных]
[Сервис уведомлений] -down-> [База данных]
[Сервис управления учетными записями] -down-> [База данных]
[Сервис вакцин] -down-> [База данных]
[Сервис управления вакцинациями] -down-> [База данных]
[Сервис для управления файлами] -down-> [База данных]




@enduml
