@startuml
actor Пользователь as user
participant "Веб-сайт Healthy" as website
participant "Сервер Healthy" as server
participant "База данных" as db

user -> website: Запрос страницы календаря прививок
website -> server: Запрос данных о прививках
server -> db: Запрос данных о прививках пользователя
db -> server: Возврат данных о прививках
server -> website: Возврат данных о прививках
website -> user: Отображение календаря прививок

user -> website: Просмотр информации о вакцине
website -> server: Запрос информации о вакцине
server -> db: Запрос данных о вакцине
db -> server: Возврат данных о вакцине
server -> website: Возврат информации о вакцине
website -> user: Отображение информации о вакцине

user -> website: Запись на вакцинацию
website -> server: Запрос на запись на вакцинацию
server -> db: Обновление данных о записи на вакцинацию
db -> server: Подтверждение обновления данных
server -> website: Подтверждение записи на вакцинацию
website -> user: Отображение подтверждения записи

@enduml
