@startuml
skinparam linetype ortho

[*] -down-> Неавторизованный

Неавторизованный -down-> Регистрация : Регистрация
Регистрация -down-> Авторизованный : Авторизация
Неавторизованный -down-> Авторизованный : Авторизация
Авторизованный -up-> Неавторизованный : Выход

Авторизованный -down-> ПросмотрКалендаря : Открыть календарь
ПросмотрКалендаря -up-> Авторизованный : Закрыть календарь

state ПросмотрКалендаря {
    [*] -down-> СписокВакцин
    СписокВакцин -down-> ПредстоящаяВакцинация : Выбор вакцины
    ПредстоящаяВакцинация -down-> ВакцинацияПройдена : Данные о вакцинации
    ПредстоящаяВакцинация : Получение уведомления
    ВакцинацияПройдена -up-> СписокВакцин : Возврат к списку

    СписокВакцин -right-> ЗавершениеСессии : Завершить сессию
}

ЗавершениеСессии -down-> [*]

@enduml
