@startuml
skinparam linetype ortho

[*] -down-> Неавторизованный

Неавторизованный -down-> Авторизованный : Успешная авторизация
Авторизованный -up-> Неавторизованный : Выход

Авторизованный -down-> ПросмотрКалендаря : Открыть календарь
ПросмотрКалендаря -up-> Авторизованный : Закрыть календарь

state ПросмотрКалендаря {
    [*] -down-> СписокВакцин
    СписокВакцин -down-> ПредстоящаяВакцинация : Выбрать вакцину
    ПредстоящаяВакцинация -down-> ВакцинацияПройдена : Ввести данные о вакцинации
    ПредстоящаяВакцинация : получить уведомление
    ВакцинацияПройдена -up-> СписокВакцин : Вернуться к списку
}

ВакцинацияПройдена -down-> Завершение : Завершить сессию
Завершение -down-> [*]

@enduml
