@startuml

[*] --> Неавторизованный

Неавторизованный --> Авторизованный : Успешная авторизация
Авторизованный --> Неавторизованный : Выход

Авторизованный --> ПросмотрКалендаря : Открыть календарь
ПросмотрКалендаря --> Авторизованный : Закрыть календарь

state ПросмотрКалендаря {
    [*] --> СписокВакцин
    СписокВакцин --> ПредстоящаяВакцинация : Выбрать вакцину
    ПредстоящаяВакцинация --> ВакцинацияПройдена : Ввести данные о вакцинации
    ПредстоящаяВакцинация : получить уведомление
    ВакцинацияПройдена --> СписокВакцин : Вернуться к списку
}

@enduml
